### PR TITLE
👌 Improve pyglotaran image

### PR DESCRIPTION
**Pull request by s-weigand**
I made some minor improvements to the [pyglotaran image](https://github.com/pan-training/Docker/tree/main/pyglotaran).
Factoring out the dependencies in a `requirents.txt` allows using [githubs dependabot to automate updates](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file) for new releases.
I set the update schedule to look for new releases each Monday at 08:00, feel free to change it to a time slot that fits better in your schedule.

In addition, we would like to have some convenience extensions for jupyter lab.

### Change summary
- [👌 Factored out pyglotaran dependencies into a requirents.txt file](https://github.com/pan-training/Docker/commit/359bdd47868bee977ef0ce6c3f5803f21b6ebcad)
- [🚇 Added dependabot config to update python distributions](https://github.com/pan-training/Docker/commit/5b540bd218fc44c4e65f6f97d4911bed4716c76d)
- [👌 Added additional jupyterlab extensions](https://github.com/pan-training/Docker/commit/6fcb9d3e9e1663ddcc4581d29cbb135e9d1b9f28)

### CODE REVIEW

**Comment by willend** [comment]
This all looks reasonable, merging

**Comment by s-weigand** [comment]
@AlexandreStefanov @willend Any chance we can get this merged and a new image pushed to docker hub until Friday?
That will be the first lecture where we use it?

**Comment by s-weigand** [comment]
For now, I changed the used versions of `pyglotaran` and `pyglotaran-extras` to use the default branch on GitHub, since @ism200 needs features that aren't released yet for his course.
After we released `0.6.0` I will open a PR to change it back installations from pip.

**Comment by willend** [comment]
Merged as requested. Rebuilding the image is something only @AlexandreStefanov can help with.

Peter

**Comment by s-weigand** [comment]
Thanks 😄

**Comment by s-weigand** [comment]
@AlexandreStefanov Thanks for pushing the new image, I just tested the notebooks and confirmed that all works 🎉

**Comment by willend** [comment]
@s-weigand great to hear! 

As I understood @ism200 is making last adjustments to the Moodle part of the material today? I have promoted him to both 'teacher' and 'manager' status - do you yourself need similar credentials for your new account?

**Pull request merged**
